---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86188.
--- DateTime: 2025/8/29 10:53
---
-- LessClick/src/Options.lua
local ADDON_NAME = ...
local LC = _G[ADDON_NAME]

local function BuildPanel(panel)
    local title = panel:CreateFontString(nil, "OVERLAY", "GameFontNormalLarge")
    title:SetPoint("TOPLEFT", 16, -16)
    title:SetText("Less Click Settings")

    local cb = CreateFrame("CheckButton", nil, panel, "InterfaceOptionsCheckButtonTemplate")
    cb:SetPoint("TOPLEFT", title, "BOTTOMLEFT", 0, -12)
    cb.Text:SetText("启用插件")
    cb:SetChecked(LC.db and LC.db.enabled)
    cb:SetScript("OnClick", function(self)
        LC.db.enabled = self:GetChecked()
    end)

    local debugCB = CreateFrame("CheckButton", nil, panel, "InterfaceOptionsCheckButtonTemplate")
    debugCB:SetPoint("TOPLEFT", cb, "BOTTOMLEFT", 0, -8)
    debugCB.Text:SetText("调试模式")
    debugCB:SetChecked(LC.db and LC.db.debug)
    debugCB:SetScript("OnClick", function(self)
        LC.db.debug = self:GetChecked()
    end)
end

local function CreateRetailCategory()
    if not Settings then return end
    local panel = CreateFrame("Frame")
    panel.name = "Less Click"
    panel:SetScript("OnShow", function()
        if panel._built then return end
        panel._built = true
        BuildPanel(panel)
    end)
    local cat = Settings.RegisterCanvasLayoutCategory(panel, "Less Click")
    cat.ID = ADDON_NAME
    Settings.RegisterAddOnCategory(cat)
    function LC.OpenOptions() Settings.OpenToCategory(cat.ID) end
end

local function CreateLegacyCategory()
    if not InterfaceOptions_AddCategory then return end
    local panel = CreateFrame("Frame", ADDON_NAME.."OptionsLegacy")
    panel.name = "Less Click"
    BuildPanel(panel)
    InterfaceOptions_AddCategory(panel)
    function LC.OpenOptions()
        InterfaceOptionsFrame_OpenToCategory(panel)
        InterfaceOptionsFrame_OpenToCategory(panel)
    end
end

C_Timer.After(0.5, function()
    if Settings then CreateRetailCategory() end
    if InterfaceOptions_AddCategory then CreateLegacyCategory() end
end)